CREATE TABLE "frontend_react_new_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "frontend_react_new_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "frontend_react_new_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "frontend_react_new_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "frontend_react_new_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "frontend_react_new_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "frontend_react_new_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "frontend_react_new_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "frontend_react_new_account" ADD CONSTRAINT "frontend_react_new_account_userId_frontend_react_new_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."frontend_react_new_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frontend_react_new_post" ADD CONSTRAINT "frontend_react_new_post_createdById_frontend_react_new_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."frontend_react_new_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frontend_react_new_session" ADD CONSTRAINT "frontend_react_new_session_userId_frontend_react_new_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."frontend_react_new_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "frontend_react_new_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "frontend_react_new_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "frontend_react_new_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "frontend_react_new_session" USING btree ("userId");